### ISSUE TITLE
Room.findAll() can not get all the rooms

### ISSUE THREAD

**Issue by Claude-Ray** [botorange/wechaty-puppet-macpro#11]
At first, `findAll()` found only one room. Now after about 1 hour, it can find three.

I have joined more than 30 rooms. It doesn't make sense to restart or re-login.

Why did it load so slowly? Is there any precondition for loading a room?

**Comment by su-chang** [comment]
Thx for issue, we are trying to resolve this problem now.

**Comment by lvxuan263** [comment]
How's it going？

**Comment by su-chang** [comment]
It's due to the `mac` protocol, the room will be loaded after message come.
