### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by yanglongji** [botorange/wechaty-puppet-macpro#18]
如何处理？

d:\cordova\wechaty\node_modules\rocksdb\deps\snappy\snappy-1.1.7\snappy-stubs-internal.h : warning C4819: 该文件包含不能在
当前代码页(93
6)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 snappy-1.1.7\snappy-stubs-internal.cc) [D:\cordova\wechaty\node_modules\rocksdb
\deps\snappy\snappy.vcxproj]
d:\cordova\wechaty\node_modules\rocksdb\deps\snappy\snappy-1.1.7\snappy-stubs-internal.h : warning C4819: 该文件包含不能在
当前代码页(93
6)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失 (编译源文件 snappy-1.1.7\snappy.cc) [D:\cordova\wechaty\node_modules\rocksdb\deps\snappy\sn
appy.vcxproj]
  snappy.vcxproj -> D:\cordova\wechaty\node_modules\rocksdb\build\Release\\snappy.lib
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed
with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\yangl\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\yangl\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\cordova\wechaty\node_modules\rocksdb
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN wechaty-puppet-macpro@0.1.17 requires a peer of wechaty-puppet@^0.15.3 but none is installed. You must install peer dependencies yourself.
npm WARN bot-wechaty@1.0.0 No description
npm WARN bot-wechaty@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rocksdb@3.1.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rocksdb@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yangl\AppData\Roaming\npm-cache\_logs\2019-09-05T02_54_14_944Z-debug.log

**Comment by ethanzyang** [comment]
@yanglongji 我遇到过这个问题, 需要你重新编译 node-gyp， 你可以加我微信 yslj755
