### ISSUE TITLE
Whether the sent video can be realized is: directly playing the video instead of the file

### ISSUE THREAD

**Issue by ethanzyang** [botorange/wechaty-puppet-macpro#20]
能否考虑实现发送视频时候，收到的是可以直接播放的视频、而不是文件。如下图

![image](https://user-images.githubusercontent.com/17006406/64355837-75846b00-d034-11e9-8d06-12a88e05ee85.png)

**Comment by su-chang** [comment]
pls check again, we have resolved this issue already. thx.
