### ISSUE TITLE
tokens for PADPRO and MACPRO not working

### ISSUE THREAD

**Issue by jimwting** [botorange/wechaty-puppet-macpro#25]
With the fix from Sep 15, we were told that our Wechat tokens should be working now.  We currently have 3 PADPRO and 17 MACPRO tokens and none of them are working.  Below are the error messages for each token type.

puppet_macpro_28a8e8512df1ad42:
The token is invalid, please use an valid token to access padchat If you have question about this, please check out our wiki: https://github.com/botorange/wechaty-puppet-padpro/wiki/Buy-Padpro-Token 你使用的Token是无效的，请你联系我们获取有效Token，详情请参考这个页面： https://github.com/botorange/wechaty-puppet-padpro/wiki/%E8%B4%AD%E4%B9%B0token

puppet_padpro_5a4e8e2dcc54fbe9:
warn: service/bot-manager.js: service/bot-manager.js: Reached timeout for bot 7eca606c-3921-4d5a-a11b-8a1fc0fc2d06 initialization and bot still not logged in. Removing bot.

**Comment by jimwting** [comment]
If we need new tokens to work with the new protocol, please send us the new tokens (total of 20)

**Comment by lijiarui** [comment]
The log shows you are not using the correct package:

Please follow the [README](https://github.com/botorange/wechaty-puppet-macpro) to install the correct package.
