### ISSUE TITLE
请指定群聊名称

### ISSUE THREAD

**Issue by lauzhihao** [botorange/wechaty-puppet-macpro#26]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: 0.28.3

- What is your wechaty-puppet-macpro version?
Answer: 0.1.22

- What is your node version? (run `node --version`)
Answer: 11.10

- What os are you using
Answer: macOSX 10.14.5

## 2. Describe the bug

Give a clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/14961045/65101601-2575b300-d9fb-11e9-8c9f-71d436e2d47b.png)

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

let fengjin = bot.Contact.load('jfeng03');
        let liuzhihao = bot.Contact.load('liuzhihao2177')
        await bot.Room.create([liuzhihao, fengjin], 'welcome')

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
10:02:12 SILL GRPC_GATEWAY 
      ===============================================================
      API Name : createRoom
      Request data : {"account":"liuzhihao2177,jfeng03","group_number":"welcome","my_account":"wxid_mrna519vu30q22"}
      Response data : {"code":0,"msg":"请指定群聊名称"}
      ===============================================================
      
10:02:12 SILL GRPC_GATEWAY error data : { code: 0, msg: '请指定群聊名称' }</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Resolved already, please check it again, thank you very much.
