### ISSUE TITLE
Invalid return value when call room.qrCode()

### ISSUE THREAD

**Issue by lauzhihao** [botorange/wechaty-puppet-macpro#27]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 0. Report Issue Guide

1. Please run the following command and check whether the problem has been fixed：

```
npm install wechaty-puppet-padlus@next
```

2. Please search in the issue first, and make sure your problem had not been reported before

## 1. Versions

- What is your wechaty version?
Answer: 0.28.3

- What is your wechaty-puppet-macpro version?
Answer: 0.1.22

- What is your node version? (run `node --version`)
Answer: 11.10

- What os are you using
Answer: macOS 10.14

## 2. Describe the bug

Give a clear and concise description of what the bug is.
![image](https://user-images.githubusercontent.com/14961045/65123029-f4aa7380-da24-11e9-8807-a825566d0351.png)
![image](https://user-images.githubusercontent.com/14961045/65123043-fffd9f00-da24-11e9-825e-e74b71923fc3.png)

Puppet interface define a roomQrcode method and mac-api/room.ts implements it, but the return value of this method change to Promise<RequestStatus> expected Promise<string>.
Now I want get the QR code of room, but this API returned status value .

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1.  room.qrcode().then(qrcode => log.info(qrcode))

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

## 6. Full Output Logs

Set env `WECHATY_LOG=silly` in order to set log level to silly, then we can get the full log (If you dosen't set log env, log level is info as default, we cannot get the full log)

**We need full log instead of log screenshot or log fragments!**

<details>
<summary>
14:39:17 SILL GRPC_GATEWAY 
      ===============================================================
      API Name : getRoomQRCode
      Request data : {"g_number":"18341181721@chatroom","my_account":"wxid_mrna519vu30q22"}
      Response data : 1
      ===============================================================
      
14:39:17 SILL MacproRoom roomQrcode message : {"code":1,"msg":"发送成功"}
</summary>

```shell
$ WECHATY_LOG=silly node yourbot.js

Question: Paste your FULL(DO NOT ONLY PROVIDE FRAGMENTS) log messages
Answer:

```

</details>

## 7. Additional context

[bug]

**Comment by su-chang** [comment]
Already resolved, please check it again, if this problem not exist, please close this issue, thank you.
