### ISSUE TITLE
扫码后，没有登录

### ISSUE THREAD

**Issue by woshidamaomao** [botorange/wechaty-puppet-macpro#30]
## 1. Versions

- What is your wechaty version?
Answer: 0.28.3

- What is your wechaty-puppet-macpro version?
Answer: 0.1.2

- What is your node version? (run `node --version`)
Answer: 10.16.0

- What os are you using
Answer: windows 10

## 2. Describe the bug
使用新注册的微信，扫码后，确认登录后，无反应，on("login")， on("message")的回调均未触发，手机微信没有显示“已登录”

## 3. To Reproduce
The script file.
`
const { Wechaty } = require('wechaty');
const {  PuppetMacpro } = require('wechaty-puppet-macpro');
const { generate } = require('qrcode-terminal');

const token = '*****************不让看不让看';

const puppet = new PuppetMacpro({
  token,
})

const bot = new Wechaty({
  puppet
});

bot.on('scan', (qrcode, status) => {
  require('qrcode-terminal').generate(qrcode, {
    small: true
  });
  const qrcodeImageUrl = [
    'https://api.qrserver.com/v1/create-qr-code/?data=',
    encodeURIComponent(qrcode),
  ].join('');
  console.log('StarterBot', '%s(%s) - %s', status, qrcodeImageUrl)
})

bot.on('message', msg => {
  console.log(`msg : ${msg}`)
})

bot.start().then(res => {
  console.log("res", res)
}).catch(err => {
  console.log('starterr', err);
})

bot.on('login', function onLogin(user) {
  console.log("用户登录：", user);
});

bot.on('logout', function onLogout(user) {
  console.log("用户退出回调：", user);
});

bot.on('error', function errorLog(error) {
  console.log("on-error", error);
});

`

## 4. Expected behavior

期望扫码后，可以正常登录，并且可以在on("message")里收到别人发的消息。

## 5. Actual behavior

实际上并没有任何反应，只有登录回调触发了，登录回调的res 打印出来是个undefind

## 6. Full Output Logs
![image](https://user-images.githubusercontent.com/21979377/65409709-015f0b00-de1b-11e9-913f-8b112bd362d2.png)

[bug]

**Comment by su-chang** [comment]
Thanks for ur issue, let's try it again.

**Comment by woshidamaomao** [comment]
> Thanks for ur issue, let's try it again.

请问该项目，还在维护吗？使用测试token，执行bot.login() 后 ，scan 二维码的回调没有被调用。

**Comment by su-chang** [comment]
请将 macpro 更新到最新版本，然后再试一下，如果仍有问题，欢迎反馈。

**Comment by woshidamaomao** [comment]
> 请将 macpro 更新到最新版本，然后再试一下，如果仍有问题，欢迎反馈。

我使用的是 + wechaty-puppet-macpro@0.1.26

**Comment by woshidamaomao** [comment]
报错信息 ERR GRPC_GATEWAY Error: 14 UNAVAILABLE: failed to connect to all addresse

**Comment by su-chang** [comment]
> 报错信息 ERR GRPC_GATEWAY Error: 14 UNAVAILABLE: failed to connect to all addresse

请描述当前状态，且提供详细信息，以便于我们来定位问题。

**Comment by woshidamaomao** [comment]
> > 报错信息 ERR GRPC_GATEWAY Error: 14 UNAVAILABLE: failed to connect to all addresse
>  
> 请描述当前状态，且提供详细信息，以便于我们来定位问题。

##### 版本信息
 - node 10.16.0
 - wechaty  0.29.2
 - wechaty-puppet-macpro 0.1.26

##### 描述 
- 启动项目后，login返回res 为undefind, 然后过了3s钟，就一直提示这个；

![image](https://user-images.githubusercontent.com/21979377/66465327-3625c000-eab3-11e9-9214-1e4ad5dc670c.png)

**Comment by su-chang** [comment]
能否成功获取到二维码？如果不能，可能是本地网络环境导致的。
