### ISSUE TITLE
实验中发现的几个问题

### ISSUE THREAD

**Issue by CooperFu** [botorange/wechaty-puppet-macpro#4]
1. roomCreate，拉群成功，但是会存在以下三个问题
    * 自定义的群聊主题不起作用，会显示默认「群聊」字样
    * 刚创建的「群聊」不会显示打招呼语
    * 控制台报错，ERR Room create() exception: Error: can not get room id, bcz no room-create event happened.

2. 在进行登录、发送和接收群聊消息等操作时，控制台会间接性的报错：UnhandledPromiseRejectionWarning: Error: can not get data from transmit server

3. 登录二维码扫描后，手机端不显示「Mac 微信已登录」提示
4. 如何才能拿到添加的好友 payload 实例

**Comment by CooperFu** [comment]
第四个问题的补充说明
```javascript
        // 添加好友
        this.addFriend = (loginedId, account, content) => __awaiter(this, void 0, void 0, function* () {
            config_1.log.silly(PRE, `addFriend(${loginedId}, ${account}, ${content})`);
            const data = {
                account: account,
                content: content,
                my_account: loginedId,
            };
            const res = yield this.requestClient.request({
                apiName: 'addFriend',
                data,
            });
            config_1.log.silly(PRE, `res : ${JSON.stringify(res)}`);
            if (res.code === schemas_1.RequestStatus.Success) {
                return schemas_1.RequestStatus.Success;
            }
            else {
                return schemas_1.RequestStatus.Fail;
            }
        });
```

这里的 res 没有之前的payload 实例了

**Comment by pdsuwwz** [comment]
* version 0.1.12
测试「拉群」时依旧会复现第（1）个问题

![Snipaste_2019-09-03_19-17-30](https://user-images.githubusercontent.com/19891724/64169173-b7b87b80-ce7f-11e9-8da1-e6f2adb2177b.png)

![Snipaste_2019-09-03_19-20-01](https://user-images.githubusercontent.com/19891724/64169225-d9b1fe00-ce7f-11e9-8efe-f67339493a95.png)

![Snipaste_2019-09-03_19-21-12](https://user-images.githubusercontent.com/19891724/64169277-0534e880-ce80-11e9-9f5c-875a247ecebc.png)
