### ISSUE TITLE
Error:can not find this room member by room id

### ISSUE THREAD

**Issue by scholar-wei** [botorange/wechaty-puppet-macpro#5]
群内只有两个人，启动bot，第一次触发message报错，之后正常

UnhandledPromiseRejectionWarning: Error: can not find this room member by room id: 17780878246@chatroom

**Comment by scholar-wei** [comment]
试了一下，所有群，第一次说话都会出现这个错误

**Comment by su-chang** [comment]
Resolved already, thank you very much.
