### ISSUE TITLE
发送小程序卡片的功能现在还支持吗？

### ISSUE THREAD

**Issue by hzzzzzz** [botorange/wechaty-puppet-macpro#68]
## 1. Versions

- What is your wechaty version?
  0.32.5

- What is your wechaty-puppet-macpro version?
  0.4.0

- What is your node version? (run `node --version`)
  10.19.0

- What os are you using
  macOs 10.15.3

## 2. Describe the bug

MiniProgram sent by `wechaty-puppet-macpro` displayed abnormal and cannot be opened in wechat mobile app (Android and IOS both):
![Screenshot_20200401-180549_WeChat](https://user-images.githubusercontent.com/12187971/78126086-879c7f80-7444-11ea-8184-85ef164ccfe1.jpg)

## 3. To Reproduce

``` js
const payload = new MiniProgram({
  username: 'foo_username',
  appid: 'foo_appid',
  title: 'testTitle',
  pagepath: 'pages/home/home',
  description: 'test',
});
try {
  await wechaty.say(payload);
} catch (err) {
  return err;
}

```

## 4. Full Output Logs
<img width="1427" alt="截屏2020-04-01下午5 56 43" src="https://user-images.githubusercontent.com/12187971/78126271-df3aeb00-7444-11ea-8eed-c1d9cb73d462.png">

**Comment by su-chang** [comment]
Of course.

Related issue: https://github.com/juzibot/wechaty-puppet-macpro/issues/61

BTW, please update `wechaty@0.35.5` and `wechaty-puppet-macpro@0.5.3`

Thank you for your issue.

**Comment by hzzzzzz** [comment]
Thanks for your reply. I'll try that.
