### ISSUE TITLE
 first use macpro , i got "ERR GRPC_GATEWAY Error: 14 UNAVAILABLE: failed to connect to all addresses"

### ISSUE THREAD

**Issue by ethanzyang** [botorange/wechaty-puppet-macpro#7]
![image](https://user-images.githubusercontent.com/17006406/64160953-6902e580-ce6f-11e9-9684-71f7d5a3c1d7.png)
I dont know why and how

**Comment by wenh7788** [comment]
1.随时更新wechaty-puppet-macpro 我看到一直有版本的迭代
2.我昨天也就是9月4号还不行9月5号我用了之前pad版本生成二维码的方式就好了（pad版本的麻烦自行搜索下呢）

**Comment by ethanzyang** [comment]
@wenh7788 我之前用 pad 版本的遇到无法登录问题，请问现在你的意思是 pad 版本可以登录了吗

**Comment by xd0612** [comment]
@jerr123 Has this issue been solved?

**Comment by ethanzyang** [comment]
@xd0612 No, Still the same

**Comment by ethanzyang** [comment]
我在 config.js 里面找到了 GRPC server 配置文件，但是让我奇怪的是这个地址根本 ping 不通

![image](https://user-images.githubusercontent.com/17006406/64325198-4e10ac80-cffa-11e9-9f45-14f4af23e3e0.png)
![image](https://user-images.githubusercontent.com/17006406/64325230-58cb4180-cffa-11e9-8509-da3b1684ae73.png)
